name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 1.8 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - if: matrix.os == 'windows-latest'
        uses: nick-invision/retry@v1
        with:
          polling_interval_seconds: 5
          timeout_minutes: 5
          max_attempts: 3
          command: choco install --no-progress make gnuwin32-coreutils.install

      - if: matrix.os == 'macos-latest'
        run: brew install maven

      - run: make test

      - run: make all

  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - run: make publish

#      - uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
#          repository: metanorma/mn-samples-bsi
#          event-type: metanorma/sts2mn
#          client-payload: '{ "ref": "${{ github.ref }}" }'
